### ISSUE TITLE
Why does `jsonapi_render` call a method called `setup_request`?

### ISSUE THREAD

**Issue by mecampbellsoup** [b2beauty/jsonapi-utils#12]
This makes no sense to me... By the time you want to invoke `jsonapi_render` the request object has been processed and you're formulating the response.

I assume you're doing it to set some context/variables that you share among your util methods, but is there another reason?

This is an example of why this puzzles and frustrates me. 

At debugger in controller:

```ruby
     8:   if creator.save
 =>  9:     binding.pry
    10:     jsonapi_render json: creator.session, status: :created
```

`jsonapi_serialize` is fine:

```ruby
[1] pry(#<Api::V1::SessionsController>)> jsonapi_serialize creator.session                                                                                                                                                                                     
{:data=>{"id"=>"9a5ad4ef-4e97-40a8-a884-daffd1c43db1", "type"=>"sessions", "links"=>{:self=>"http://example.org/api/v1/sessions/9a5ad4ef-4e97-40a8-a884-daffd1c43db1"}, "relationships"=>{"credential"=>{:links=>{:self=>"http://example.org/api/v1/sessions/9a5ad4ef-4e97-40a8-a884-daffd1c43db1/relationships/credential", :related=>"http://example.org/api/v1/sessions/9a5ad4ef-4e97-40a8-a884-daffd1c43db1/credential"}}}}}
```

`jsonapi_render` is not:

```ruby
[3] pry(#<Api::V1::SessionsController>)> jsonapi_render json: creator.session, status: :created
"{\"errors\":[{\"title\":\"Param not allowed\",\"detail\":\"email is not allowed.\",\"id\":null,\"href\":null,\"code\":\"105\",\"source\":null,\"links\":null,\"status\":\"400\",\"meta\":null},{\"title\":\"Param not allowed\",\"detail\":\"password is not allowed.\",\"id\":null,\"href\":null,\"code\":\"105\",\"source\":null,\"links\":null,\"status\":\"400\",\"meta\":null}]}"
```

Sorry for venting a bit here. I just don't understand why we need to have such an explicit tie between the request and the response. Depending on the application they may not share parameters, like in our case.

**Comment by tiagopog** [comment]
Hi, @mecampbellsoup. The implementation was due to  change of how `jsonapi-resources` deals with the setup of requests. I came across this bug few days ago but I had hard days at work and got no time to take a look on it. Anyway, I'll probably work on a fix today or, at most, tomorrow.
