### ISSUE TITLE
@request not getting set properly

### ISSUE THREAD

**Issue by mecampbellsoup** [b2beauty/jsonapi-utils#14]
In our application resource controller:

```ruby
     7:   if creator.save
 =>  8:     binding.pry
     9:     jsonapi_render json: creator.application, status: :created
    10:   else
```

Calling `#jsonapi_serialize` to check what the issue is:

```ruby
    149: def turn_into_resource(record, options = {})
    150:   if options[:resource]
    151:     options[:resource].to_s.constantize.new(record, context)
    152:   else
 => 153:     binding.pry
    154:     @request.resource_klass.new(record, context)
    155:   end

[1] pry(#<Api::V1::ApplicationsController>)> @request
=> nil
```

**Comment by mecampbellsoup** [comment]
@tiagopog FYI

**Comment by tiagopog** [comment]
Weird, since the `@request` instance variable is [set up before the action](https://github.com/b2beauty/jsonapi-utils/blob/master/lib/jsonapi/utils.rb#L9) gets executed. I'll take a look on this later today. Thanks, @mecampbellsoup!

**Comment by mecampbellsoup** [comment]
@tiagopog it's a Rails 5 `ApplicationController` thing:

```ruby
[1] pry(JSONAPI::Utils)> base
=> Api::V1::BaseController
[2] pry(JSONAPI::Utils)> base.respond_to? :helper_method
=> false
[3] pry(JSONAPI::Utils)> base.superclass
=> ApplicationController
[4] pry(JSONAPI::Utils)> base.superclass.respond_to? :helper_method
=> false
[5] pry(JSONAPI::Utils)> ActionController::Base.respond_to? :helper_method
=> true
```

**Comment by mecampbellsoup** [comment]
@tiagopog and here's another breaking commit:

https://github.com/cerebris/jsonapi-resources/commit/f8dcf8558a1c2d8018a22f74fd0514d0779b5bb9

You need to change `JSONAPI::Request` to `JSONAPI::RequestParser`.

**Comment by mecampbellsoup** [comment]
This bug ^^ is happening in our codebase because we track master of `jsonapi-resources` gem.

**Comment by mecampbellsoup** [comment]
@tiagopog further, I think that `helper_method` is only used by non-API Rails apps. We are using `rails-api`, makes sense we don't have `helper_method` exposed in our controllers as such.

**Comment by tiagopog** [comment]
Since Rails 5 and JR's master are not supported by JU, this issue will be closed and a branch will be created for future support to their breaking changes.

**Comment by mecampbellsoup** [comment]
@tiagopog Shouldn't `jsonapi-utils` master have `jsonapi-resources` *master* as a dep though?
