### ISSUE TITLE
Getting the id from the object instance still not working properly

### ISSUE THREAD

**Issue by mecampbellsoup** [b2beauty/jsonapi-utils#16]
```
     Failure/Error: expect(response_body).to eq({
       
       expected: "{\"errors\":[{\"title\":\"Record not found\",\"detail\":\"The record identified by 06264908-21e5-4a1e-9d33-2eeb3eb0ba88 could not be found.\",\"id\":null,\"href\":null,\"code\":\"404\",\"source\":null,\"links\":null,\"status\":\"404\",\"meta\":null}]}"
            got: "{\"errors\":[{\"title\":\"Record not found\",\"detail\":\"The record identified by (no identifier) could not be found.\",\"code\":\"404\",\"status\":\"404\"}]}"
```

**Comment by mecampbellsoup** [comment]
@tiagopog usage in our controller:

```ruby
  def show
    jsonapi_render json: application, status: :ok
  end
```

**Comment by mecampbellsoup** [comment]
@tiagopog disregard my previous comment. This is coming from usage of `jsonapi_render_not_found`:

```ruby
  rescue_from ActiveRecord::RecordNotFound, with: :jsonapi_render_not_found
```

**Comment by tiagopog** [comment]
No problem, @mecampbellsoup. Keep me in the loop if anything goes wrong with your tests.

**Comment by mecampbellsoup** [comment]
@tiagopog why did you close this?

**Comment by tiagopog** [comment]
@mecampbellsoup I understood that there were no actual errors. If it isn't so, could you please give me more details?

**Comment by mecampbellsoup** [comment]
See the `got` output in the RSpec output above.

**Comment by mecampbellsoup** [comment]
It's not grabbing the ID from the request - this was the first "bug" I notified you about when we started working on/with your gem.

**Comment by tiagopog** [comment]
Well, the gem is far from its v1.0 so bugs may happen along the way. Since it has tests covering the behavior you related in this issue, I would appreciate if you could come with more details of this failing test case, like the request's params.

**Comment by mecampbellsoup** [comment]
@tiagopog yea no worries, just wanted to keep the issue open for now. I'll try to more info soon, it's hard to tell with master moving for both `jsonapi-resources` and `jsonapi-utils` whether this issue is still happening or not. Gimme' some time on this.

**Comment by tiagopog** [comment]
@mecampbellsoup do you have any news about this issue?

**Comment by tiagopog** [comment]
@mecampbellsoup I will close this issue since there is no evidence that the reported bug is happening. Please, let us know if anything goes wrong again.
