### ISSUE TITLE
Error codes must be strings

### ISSUE THREAD

**Issue by halilim** [b2beauty/jsonapi-utils#17]
According to the [spec](http://jsonapi.org/format/#error-objects), `code`s in the [exceptions](https://github.com/b2beauty/jsonapi-utils/blob/master/lib/jsonapi/utils/exceptions.rb) must be strings. Currently generated errors aren't  valid against the [JSON API Schema](http://jsonapi.org/schema). See https://github.com/cerebris/jsonapi-resources/issues/675. An example:
```json
{
  "errors": [
    {
      "title": "Bad Request",
      "detail": "This request is not supported.",
      "code": 400,
      "status": "400"
    }
  ]
}
```

**Comment by tiagopog** [comment]
Thanks for the feedback, @halilim. I may come up with a PR in few hours.
