### ISSUE TITLE
Possible to jsonapi_render and pass an `include` option?

### ISSUE THREAD

**Issue by mecampbellsoup** [b2beauty/jsonapi-utils#19]
I need to render an `Application` instance (AR::Base inherited) which has associated `users`. 

I want to side-load those users, i.e. have them serialized beneath an `included` key, following this type of pattern:
```
{
  "data": {
    "type": "application",
    "id": "f18ba709-4903-4024-856d-cb0a4539f498",
    "links": {
      "self": "https://sandbox.opentransact.com/v1/applications/f18ba709-4903-4024-856d-cb0a4539f498"
    },
    "attributes": {
      "name": "Zipmark, Inc. Deposit Application"
    },
    "relationships": {
      "users": {
        "data": [
          { "type": "user", "id": "de4a83b6-ba4f-40db-89d2-a5c4078d9a19" }
        ]
      }
  },
  "included": [{
    "type": "user",
    "id": "de4a83b6-ba4f-40db-89d2-a5c4078d9a19",
    "links": {
      "self": "https://sandbox.opentransact.com/v1/users/de4a83b6-ba4f-40db-89d2-a5c4078d9a19"
    },
    "attributes": {
      "email": "james@zipmark.com",
      "password": "password",
      "name": "James Dean"
    }
  }
}
```
I tried invoking it as `jsonapi_render json: application, include: ['credentials']` which is [how `jsonapi-resources` does it](https://github.com/cerebris/jsonapi-resources#include). 

Is this possible?

**Comment by tiagopog** [comment]
@mecampbellsoup it's not possible because when you are using the `jsonapi_(render|format|serialize)` method you don't actually need to pass any additional argument in order to get included the related resources or make things like sort, filter and fields work. JU + JR automatically validate and interpret your request params to generate the response you're expecting. It's all about passing the query string params – such as `include` – and then you get the JSON with the included resources.

**Comment by chrisdpeters** [comment]
@tiagopog [This comment](https://github.com/cerebris/jsonapi-resources/issues/389#issuecomment-135782835) pulls a relevant quote from the JSON API spec:

> **Inclusion of Related Resources**

> An endpoint MAY return resources related to the primary data by default.

> An endpoint MAY also support an include request parameter to allow the client to customize which related resources should be returned.

> If an endpoint does not support the include parameter, it must respond with 400 Bad Request to any requests that include it.

> If an endpoint supports the include parameter and a client supplies it, the server MUST NOT include unrequested resource objects in the included section of the compound document.

I really like the gist of what [this other comment](https://github.com/cerebris/jsonapi-resources/issues/389#issuecomment-176303658) is suggesting.

When I try something like this, it doesn't include the related record though:

```ruby
params[:include] ||= 'draft'
jsonapi_render json: page
```

Is this something that could be worked into JSONAPI::Utils?

**Comment by tiagopog** [comment]
@chrisdpeters up to now JU does not support a default value for the include query string param, but I'm willing to do such implementation for the v0.5.0 milestone. We could open a new thread and start a further discussion about the feature's details. What do you think?

**Comment by chrisdpeters** [comment]
@tiagopog 👍  Opened a new issue: #36.

**Comment by adambedford** [comment]
@tiagopog Are you saying that includes should "just work" then? i.e. if I have `jsonapi_render json: @resource` and there are include directives in the `params`, it'll return them?

**Comment by tiagopog** [comment]
@adambedford yes, this should work properly.

So if you want a relationship to be included by default for a given controller action you could call a `before_action` callback on that action merging then the required default related resource to `params[:included]`.

Try something like that:

```ruby
before_action :include_default_relationships, on: :index

def index 
  jsonapi_render json: User.all
end

private

def include_default_relationships
  included = params[:included].to_s.split(',')
  params[:included] = (included | %w(author posts)).join(',')
end
```
