### ISSUE TITLE
jsonapi-resources internal Request API brings breaking change in 0.7.1 betas

### ISSUE THREAD

**Issue by Azolo** [b2beauty/jsonapi-utils#20]
In the [jsonapi-resources version `0.7.1.beta2`][1] there's a breaking change removes the `JSONAPI::Request` class.

Just a heads up because you may want to lock the current version to `0.7.0` in that case.

[1]: https://github.com/cerebris/jsonapi-resources/tree/a3bdbb94c3c4a6ca966f1386ddfc1466f2cfde40/lib/jsonapi

**Comment by tiagopog** [comment]
@Azolo, this change is already in our radar and may be package in a coming beta version of `jsonapi-utils` with support to the breaking changes from `jsonapi-resources` `0.7.1`. For now, we strongly recommend everyone to keep using "stable" versions of `jsonapi-resources` (preferably `0.7.0`). Thanks for reporting :-)
